import './globals.css'
import { Rubik } from 'next/font/google'
import { Providers } from './providers'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js 13 and Chakra UI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
